 /******************************************************************************
 *
 * Module: ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: Header file for the ultrasonic sensor
 *
 * Author: Mohamed Yahia
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

extern volatile int distance;
extern volatile int g_edgeCount;
extern volatile int g_timeHigh;

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define Ultra_Trigger_PORT_ID          PORTB_ID
#define Ultra_Trigger_PIN_ID           PIN5_ID

#define Ultra_Echo_PORT_ID             PORTD_ID
#define Ultra_Echo_PIN_ID              PIN6_ID


/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/


/*
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);

/*
 *  Send the Trigger pulse to the ultrasonic.
 */

void Ultrasonic_Trigger(void);

/*
 *   Send the trigger pulse by using Ultrasonic_Trigger function.
 *   Start the measurements by the ICU from this moment.
 */

uint16 Ultrasonic_readDistance(void);


/*
 *   This is the call back function called by the ICU driver.
 *   This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
